name: symfony-downstreamer-2
recipe: symfony

services:
  database:
    type: symfony-mysql:8.0

# do not remove this
plugins:
  "@lando/symfony": ../..
  "@lando/mysql": ../../node_modules/@lando/mysql
